version: '3.7'
services:
  mysql-development:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'Password@123'
      MYSQL_ROOT_USER: 'root' 
      MYSQL_DATABASE: perlego_test_db
      MYSQL_PASSWORD: 'Password@123'
    ports:
      - "3306:3306"
  admin:    
    image: adminer    
    ports:      
      - "8080:8080"
      